/* Main.c file generated by New Project wizard
 *
 * Created:   Vie May 13 2016
 * Processor: PIC16F877
 * Compiler:  CCS for PIC
 */

#include <16F877.h>
#include <rotar.h>
#use	delay	(clock = 4000000)
#byte	prta =	0x05
#byte	prtb	=	0x06
#byte	prtc =	0x07
#byte	prtd	=	0x08
#byte	prte	=	0x09
#byte	adcon	=	0x9f
#byte	tra 	=	0x85
#byte	trb	=	0x86
#byte	trc 	=	0x87
#byte	trd	=	0x88
#byte	tre	=	0x89
#byte	fsr	=	0x04
#byte	status	=	0x03
#byte	pc	=	0x02
#byte	indf	=	0x00

int  efcd[8] = {0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff};
int  efce[8] = {0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff};
int  efcf[8] = {0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff};

//	A
int  efc1[8] = {
	0b11111111,
	0b11000011,
	0b11011011,
	0b11000011,
	0b11011011,
	0b11011011,
	0b11111111,
	0b11111111};

//	B
int  efc2[8] = {
	0b11111111,
	0b11000111,
	0b11011011,
	0b11000111,
	0b11011011,
	0b11000111,
	0b11111111,
	0b11111111};
//	C
int  efc3[8] = {
	0b11111111,
	0b11000011,
	0b11011111,
	0b11011111,
	0b11011111,
	0b11000011,
	0b11111111,
	0b11111111};
//	D
int  efc4[8] = {
	0b11111111,
	0b11000111,
	0b11011011,
	0b11011011,
	0b11011011,
	0b11000111,
	0b11111111,
	0b11111111};
//	E
int  efc5[8] = {
	0b11111111,
	0b11000011,
	0b11011111,
	0b11000011,
	0b11011111,
	0b11000011,
	0b11111111,
	0b11111111};

//	F
int  efc6[8] = {
	0b11111111,
	0b11000011,
	0b11011111,
	0b11000011,
	0b11011111,
	0b11011111,
	0b11111111,
	0b11111111};
	
//	G
	int  efc7[8] = {
	0b11111111,
	0b11000011,
	0b11011111,
	0b11010011,
	0b11011011,
	0b11000011,
	0b11111111,
	0b11111111};
//	H
	int  efc8[8] = {
	0b11111111,
	0b11011011,
	0b11011011,
	0b11000011,
	0b11011011,
	0b11011011,
	0b11111111,
	0b11111111};
//	I
	int  efc9[8] = {
	0b11111111,
	0b11000111,
	0b11101111,
	0b11101111,
	0b11101111,
	0b11000111,
	0b11111111,
	0b11111111};
//	J
	int  efc10[8] = {
	0b11111111,
	0b11100011,
	0b11110111,
	0b11110111,
	0b11110111,
	0b11000111,
	0b11111111,
	0b11111111};
//	K
	int  efc11[8] = {
	0b11111111,
	0b11011011,
	0b11010111,
	0b11001111,
	0b11010111,
	0b11011011,
	0b11111111,
	0b11111111};
//	L
	int  efc12[8] = {
	0b11111111,
	0b11011111,
	0b11011111,
	0b11011111,
	0b11011111,
	0b11000011,
	0b11111111,
	0b11111111};
	
	
	


// Subrutina: Efecto para la matriz 
int	efecto(int op2, int g, int ef)
{
	if(op2==0)
	{
			if	(ef==0)
			{
				return efcd[g];
			}
			else	if	(ef==1)
			{
				return efc8[g];
			}
			else	if	(ef==2)
			{
	
				return efc2[g];
			}
			else	if	(ef==3)
			{
		
				return efc5[g];
			}
			else	if	(ef==4)
			{
				return efc3[g];
			}
			else	if	(ef==5)
			{
				return efc6[g];
			}
			else	if	(ef==6)
			{
				return efc4[g];
			}
			else	if	(ef==7)
			{
				return efc7[g];
			}
			else	return	0;
	}
		
	else	if	(op2==1)
	{	
			if	(ef==0)
			{
				return efce[g];
			}
			
			else	if	(ef==1)
			{
				return efc9[g];
			}
			else	if	(ef==2)
			{
	
				return efc10[g];
			}
			else	if	(ef==3)
			{
		
				return efc12[g];
			}
			else	if	(ef==4)
			{
				return efc5[g];
			}
			else	if	(ef==5)
			{
				return efc4[g];
			}
			else	if	(ef==6)
			{
				return efc1[g];
			}
			else	if	(ef==7)
			{
				return efc3[g];
			}
			else	return	0;
	}
	
	else	if	(op2==2)
	{
			if	(ef==0)
			{
				return efcf[g];
			}
			
			else	if	(ef==1)
			{
				return efc8[g];
			}
			else	if	(ef==2)
			{
	
				return efc10[g];
			}
			else	if	(ef==3)
			{
		
				return efc9[g];
			}
			else	if	(ef==4)
			{
				return efc11[g];
			}
			else	if	(ef==5)
			{
				return efc7[g];
			}
			else	if	(ef==6)
			{
				return efc1[g];
			}
			else	if	(ef==7)
			{
				return efc2[g];
			}
			else	return	0;
	}
}


//Subrutina: Muestra los datos en la matriz
int	mostrar( int efi, int pt1, int pt2, int pt3)
{
	int	alt=7, vef, cdi,tdi,rdi,t=6;
	
	cdi=8, tdi=0x01;
	for(int c=0;c<8;c=c+4)
	{
			
			
			while(cdi>0)
			{		
					prte=0x00;
				
					vef= efecto(0,cdi-1,efi);
					if	(pt1==1)	prtb=	vef;
					else	prtb=	0xff;
				
					vef= efecto(1,cdi-1,efi);
					if	(pt2==1)	prtc=	vef;
					else	prtc=	0xff;
				
					vef= efecto(2,cdi-1,efi);
					if	(pt3==1)	prtd=	vef;
					else	prtd=	0xff;
				
					prte=0x01;
					
					prtb=tdi;
				
					prte=0x02;
			
					tdi=tdi<<1;
					bit_clear(tdi,0);
					delay_ms(t);
					prtb=0xff;
					
					prte=0x01;			
					prtb=0x00;		
					prte=0x02;
					cdi=cdi-1;		
			}		
			
	}

	return	0;
}

	//******************************************//
  //				Inicio de la funcion principal				  //
//******************************************//

int main (void)

 {
		//Configuracion de puertos
	 adcon	=	0x86;
	 tra		=	0x07;
	 trb		=	0x00;
	 trc		=	0x00;
	 trd		=	0x00;
	 tre		=	0x00;

/*
	INFO:	camb: Activa el cambio entre efectos (0=off ; 1=on )
				rota:	 Mueve los efctos etre las matrices (0=off; 1=on)
				rvlo:	Numero de ciclos a repetir
				pt1, pt2, pt3: Enciende/Apaga las matrices (0=off; 1=on)
				brot: Rota hacia Derecha/Izquierda (0=izq; 1=der)
*/
int  ee2=1,vlv=0,cont=1,camb=0 ,rota=0, rvlo=20,pt1=1,pt2=1,pt3=1,brot=1;

camb=bit_test(prta,2);
do
{
rota=bit_test(prta,0);
brot=bit_test(prta,1);
if(camb==7) camb=bit_test(prta,2);
pt1=bit_test(prta,3);
pt2=bit_test(prta,4);
pt3=bit_test(prta,5);


int	v=0,valu,valu2,r1,r2;

if(rota==1 )	rvlo=3;
if(camb>0) rvlo=50;
	//Retardo entre efectos
{
	if	(ee2==5) ee2=1;
	if	(camb>7)camb=1;
	for(int o=0;o<rvlo;o++)
	{
		
		mostrar(camb,pt3,pt2,pt1);	
	}
		//Rota/mueve los efectos entre las matrices
		
		v=0;
		vlv=vlv+1;
		if	(brot==1)	{r1=0; r2=7;}
		else	{r1=7;	r2=0;}
		while(v<8 && rota ==1)
		{
			
			if(vlv==8)	cont=cont+1;
			
			if(cont==12)	cont=1;
			
			if(vlv>=8) {vlv=0;}
			
			//Rota efc
			if	(brot==0)	
				{
					efcf[v]=efcf[v]<<1;
					valu=bit_test(efce[v],r1);
					if	(valu==1)	bit_set(efcf[v],r2);
					else		bit_clear(efcf[v],r2);
				}
			else
			{
				efcd[v]=efcd[v]>>1;
				valu=bit_test(efce[v],r1);
				if	(valu==1)	bit_set(efcd[v],r2);
				else		bit_clear(efcd[v],r2);
				
			}	

			
			//Rota efc
			if	(brot==0)
			{
				efce[v]=efce[v]<<1;
				valu=bit_test(efcd[v],r1);
				if	(valu==1)	bit_set(efce[v],r2);
				else		bit_clear(efce[v],r2);
			}
			
			else
			{
				efce[v]=efce[v]>>1;
				valu=bit_test(efcf[v],r1);
				if	(valu==1)	bit_set(efce[v],r2);
				else		bit_clear(efce[v],r2);
				
			}	
			
			
			//Rota efc
			if	(brot==0)	efcd[v]=efcd[v]<<1;
					
			
			else	efcf[v]=efcf[v]>>1;
				
				
				
			if(cont==1)
			{
				if	(brot==0)
				{
				valu=	bit_test(efc1[v],7);
				if	(valu==1)	bit_set(efcd[v],0);
				else			bit_clear(efcd[v],0);
				efc1[v] = op(6,efc1[v],v,0);
				}
				
			else
				{
				valu=	bit_test(efc1[v],0);
				if	(valu==1)	bit_set(efcf[v],7);
				else			bit_clear(efcf[v],7);
				efc1[v] = op(6,efc1[v],v,1);
				}
			}
				
			if(cont==2)
							{
				if	(brot==0)
				{
				valu=	bit_test(efc2[v],7);
				if	(valu==1)	bit_set(efcd[v],0);
				else			bit_clear(efcd[v],0);
				efc2[v] = op(6,efc2[v],v,0);
				}
				
			else
				{
				valu=	bit_test(efc2[v],0);
				if	(valu==1)	bit_set(efcf[v],7);
				else			bit_clear(efcf[v],7);
				efc2[v] = op(6,efc2[v],v,1);
				}
			}

			if(cont==3)
			{
				if	(brot==0)
				{
				valu=	bit_test(efc3[v],7);
				if	(valu==1)	bit_set(efcd[v],0);
				else			bit_clear(efcd[v],0);
				efc3[v] = op(6,efc3[v],v,0);
				}
				
			else
				{
				valu=	bit_test(efc3[v],0);
				if	(valu==1)	bit_set(efcf[v],7);
				else			bit_clear(efcf[v],7);
				efc3[v] = op(6,efc3[v],v,1);
				}
			}

			if(cont==4)
			{
				if	(brot==0)
				{
				valu=	bit_test(efc4[v],7);
				if	(valu==1)	bit_set(efcd[v],0);
				else			bit_clear(efcd[v],0);
				efc4[v] = op(6,efc4[v],v,0);
				}
				
			else
				{
				valu=	bit_test(efc4[v],0);
				if	(valu==1)	bit_set(efcf[v],7);
				else			bit_clear(efcf[v],7);
				efc4[v] = op(6,efc4[v],v,1);
				}
			}

			if(cont==5)
			{
				if	(brot==0)
				{
				valu=	bit_test(efc5[v],7);
				if	(valu==1)	bit_set(efcd[v],0);
				else			bit_clear(efcd[v],0);
				efc5[v] = op(6,efc5[v],v,0);
				}
				
			else
				{
				valu=	bit_test(efc5[v],0);
				if	(valu==1)	bit_set(efcf[v],7);
				else			bit_clear(efcf[v],7);
				efc5[v] = op(6,efc5[v],v,1);
				}
			}

			if(cont==6)
			{
				if	(brot==0)
				{
				valu=	bit_test(efc6[v],7);
				if	(valu==1)	bit_set(efcd[v],0);
				else			bit_clear(efcd[v],0);
				efc6[v] = op(6,efc6[v],v,0);
				}
				
			else
				{
				valu=	bit_test(efc6[v],0);
				if	(valu==1)	bit_set(efcf[v],7);
				else			bit_clear(efcf[v],7);
				efc6[v] = op(6,efc6[v],v,1);
				}
			}
			
			if(cont==7)
			{
				if	(brot==0)
				{
				valu=	bit_test(efc7[v],7);
				if	(valu==1)	bit_set(efcd[v],0);
				else			bit_clear(efcd[v],0);
				efc7[v] = op(6,efc7[v],v,0);
				}
				
			else
				{
				valu=	bit_test(efc7[v],0);
				if	(valu==1)	bit_set(efcf[v],7);
				else			bit_clear(efcf[v],7);
				efc7[v] = op(6,efc7[v],v,1);
				}
			}
			
			if(cont==8)
			{
				if	(brot==0)
				{
				valu=	bit_test(efc8[v],7);
				if	(valu==1)	bit_set(efcd[v],0);
				else			bit_clear(efcd[v],0);
				efc8[v] = op(6,efc8[v],v,0);
				}
				
			else
				{
				valu=	bit_test(efc8[v],0);
				if	(valu==1)	bit_set(efcf[v],7);
				else			bit_clear(efcf[v],7);
				efc8[v] = op(6,efc8[v],v,1);
				}
			}
			
			if(cont==9)
			{
				if	(brot==0)
				{
				valu=	bit_test(efc9[v],7);
				if	(valu==1)	bit_set(efcd[v],0);
				else			bit_clear(efcd[v],0);
				efc9[v] = op(6,efc9[v],v,0);
				}
				
			else
				{
				valu=	bit_test(efc9[v],0);
				if	(valu==1)	bit_set(efcf[v],7);
				else			bit_clear(efcf[v],7);
				efc9[v] = op(6,efc9[v],v,1);
				}
			}
			
			if(cont==10)
			{
				if	(brot==0)
				{
				valu=	bit_test(efc10[v],7);
				if	(valu==1)	bit_set(efcd[v],0);
				else			bit_clear(efcd[v],0);
				efc10[v] = op(6,efc10[v],v,0);
				}
				
			else
				{
				valu=	bit_test(efc10[v],0);
				if	(valu==1)	bit_set(efcf[v],7);
				else			bit_clear(efcf[v],7);
				efc10[v] = op(6,efc10[v],v,1);
				}
			}
			
			if(cont==11)
			{
				if	(brot==0)
				{
				valu=	bit_test(efc11[v],7);
				if	(valu==1)	bit_set(efcd[v],0);
				else			bit_clear(efcd[v],0);
				efc11[v] = op(6,efc11[v],v,0);
				}
				
			else
				{
				valu=	bit_test(efc11[v],0);
				if	(valu==1)	bit_set(efcf[v],7);
				else			bit_clear(efcf[v],7);
				efc11[v] = op(6,efc11[v],v,1);
				}
			}
			
			
					
			v=v+1;	
		}
	
		ee2=ee2+1;

}
	if(camb!=0) camb=camb+1;
}
		
    while (1);
		
  return 0;
 }   
